# Generated by Django 3.2 on 2021-05-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20210502_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='text',
            field=models.TextField(),
        ),
    ]
