# Generated by Django 3.2 on 2021-05-04 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='text',
            new_name='name',
        ),
    ]
