# Generated by Django 3.2 on 2021-05-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_auto_20210503_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='pizza',
        ),
    ]
